# Generated by Django 3.2.20 on 2023-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemontype',
            name='type_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
