# Generated by Django 3.2.20 on 2023-07-29 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemonability",
            old_name="pokemon_id",
            new_name="pokemon",
        ),
        migrations.RenameField(
            model_name="pokemonstats",
            old_name="pokemon_id",
            new_name="pokemon",
        ),
        migrations.RenameField(
            model_name="pokemontype",
            old_name="pokemon_id",
            new_name="pokemon",
        ),
    ]
